# Generated by Django 5.2.12 on 2026-03-25 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text="Unique machine slug, e.g. 'payment_stripe'.", max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('payment', 'Payment'), ('notification', 'Notification'), ('shipping', 'Shipping'), ('catalog', 'Catalog'), ('order', 'Order'), ('analytics', 'Analytics'), ('marketing', 'Marketing'), ('security', 'Security'), ('general', 'General')], default='general', max_length=20)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=15)),
                ('requires_config', models.BooleanField(default=False, help_text='If True, this feature needs an active ProviderConfig to function.')),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema describing required ProviderConfig keys.')),
                ('is_available', models.BooleanField(default=True, help_text='Global kill-switch. False = never available regardless of flags.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text (multiline)')], default='string', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('branding', 'Branding'), ('payment', 'Payment'), ('notification', 'Notification'), ('shipping', 'Shipping'), ('inventory', 'Inventory'), ('returns', 'Returns'), ('seo', 'SEO'), ('advanced', 'Advanced')], default='general', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Human-readable display label.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True, exposed via the public /settings/ endpoint.')),
                ('is_editable', models.BooleanField(default=True, help_text='Set False to lock a setting against admin edits.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app setting',
                'verbose_name_plural': 'app settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100, help_text='0=disabled, 100=all users, 1-99=gradual rollout.')),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags_enabled', to=settings.AUTH_USER_MODEL)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='features.feature')),
            ],
            options={
                'verbose_name': 'feature flag',
                'verbose_name_plural': 'feature flags',
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.SlugField(help_text="Provider slug, e.g. 'stripe', 'cashfree'.", max_length=60)),
                ('config', models.JSONField(default=dict, help_text='Provider credentials/settings.')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_configs', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='features.feature')),
            ],
            options={
                'verbose_name': 'provider config',
                'verbose_name_plural': 'provider configs',
                'ordering': ['feature__code', 'provider_key'],
                'unique_together': {('feature', 'provider_key')},
            },
        ),
    ]
