# Generated by Django 5.2.12 on 2026-03-25 08:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Return Policy', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_return_days', models.PositiveSmallIntegerField(default=7, help_text='Number of days after delivery within which a return can be submitted.')),
                ('max_exchange_days', models.PositiveSmallIntegerField(default=14, help_text='Number of days after delivery within which an exchange can be submitted.')),
                ('eligible_order_statuses', models.JSONField(default=list, help_text='Order statuses eligible for return, e.g. ["delivered","completed"]')),
                ('non_returnable_category_ids', models.JSONField(default=list, help_text='List of category UUIDs whose products cannot be returned.')),
                ('non_returnable_reason', models.TextField(blank=True, default='This product is not eligible for return.')),
                ('restocking_fee_pct', models.DecimalField(decimal_places=2, default=0, help_text='Restocking fee as a % of order item price (deducted from refund).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('requires_original_packaging', models.BooleanField(default=False)),
                ('category_overrides', models.JSONField(blank=True, default=list, help_text='Per-category policy overrides.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'return policy',
                'verbose_name_plural': 'return policies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('items_received', 'Items Received'), ('inspected', 'Inspected'), ('rejected_after_inspection', 'Rejected After Inspection'), ('exchange_shipped', 'Exchange Shipped'), ('completed', 'Completed')], db_index=True, default='submitted', max_length=30)),
                ('return_tracking_no', models.CharField(blank=True, max_length=200)),
                ('return_carrier', models.CharField(blank=True, max_length=100)),
                ('exchange_tracking_no', models.CharField(blank=True, max_length=200)),
                ('exchange_carrier', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('items_received_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_shipped_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exchange request',
                'verbose_name_plural': 'exchange requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('reason_code', models.CharField(choices=[('defective', 'Product is defective / not working'), ('damaged_transit', 'Damaged during shipping'), ('wrong_item', 'Wrong item sent'), ('not_as_described', 'Not as described / pictured'), ('changed_mind', 'Changed my mind'), ('size_issue', 'Size / fit issue'), ('quality_issue', 'Quality not satisfactory'), ('duplicate_order', 'Ordered by mistake / duplicate'), ('late_delivery', 'Delivered too late'), ('other', 'Other')], max_length=30)),
                ('reason_detail', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good — returned as-is, resellable'), ('minor_damage', 'Minor damage — refurbish needed'), ('damaged', 'Damaged — cannot be resold'), ('unusable', 'Unusable / destroyed'), ('missing_parts', 'Missing parts / accessories')], max_length=20)),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, help_text='Positive = customer owes; Negative = we owe customer.', max_digits=10)),
                ('stock_reintegrated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_items', to='orders.orderitem')),
                ('original_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_returns', to='catalog.productvariant')),
                ('replacement_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_replacements', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
                ('exchange_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.exchangerequest')),
            ],
            options={
                'verbose_name': 'exchange item',
                'verbose_name_plural': 'exchange items',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('items_received', 'Items Received'), ('inspected', 'Inspected'), ('rejected_after_inspection', 'Rejected After Inspection'), ('refund_initiated', 'Refund Initiated'), ('completed', 'Completed')], db_index=True, default='submitted', max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('restocking_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_refund_ready', models.BooleanField(db_index=True, default=False)),
                ('pickup_address', models.JSONField(blank=True, default=dict)),
                ('return_tracking_no', models.CharField(blank=True, max_length=200)),
                ('return_carrier', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Customer notes.')),
                ('staff_notes', models.TextField(blank=True, help_text='Internal staff notes.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('items_received_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('refund_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order')),
                ('refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_refunds', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'return request',
                'verbose_name_plural': 'return requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('reason_code', models.CharField(choices=[('defective', 'Product is defective / not working'), ('damaged_transit', 'Damaged during shipping'), ('wrong_item', 'Wrong item sent'), ('not_as_described', 'Not as described / pictured'), ('changed_mind', 'Changed my mind'), ('size_issue', 'Size / fit issue'), ('quality_issue', 'Quality not satisfactory'), ('duplicate_order', 'Ordered by mistake / duplicate'), ('late_delivery', 'Delivered too late'), ('other', 'Other')], max_length=30)),
                ('reason_detail', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good — returned as-is, resellable'), ('minor_damage', 'Minor damage — refurbish needed'), ('damaged', 'Damaged — cannot be resold'), ('unusable', 'Unusable / destroyed'), ('missing_parts', 'Missing parts / accessories')], help_text='Filled in by staff when items are received.', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_reintegrated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse to reintegrate stock into.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
            options={
                'verbose_name': 'return item',
                'verbose_name_plural': 'return items',
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_transitions', to=settings.AUTH_USER_MODEL)),
                ('exchange_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='returns.exchangerequest')),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
