# Generated by Django 5.2.12 on 2026-03-25 08:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Retail Store'), ('virtual', 'Virtual / Dropship')], default='warehouse', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouses',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'warehouse stock',
                'verbose_name_plural': 'warehouse stocks',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_type', models.CharField(choices=[('order', 'Order'), ('return', 'Return'), ('exchange', 'Exchange'), ('transfer', 'Transfer'), ('manual', 'Manual'), ('system', 'System')], max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('committed', 'Committed'), ('released', 'Released')], db_index=True, default='active', max_length=15)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-release after this time if still ACTIVE.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehousestock')),
            ],
            options={
                'verbose_name': 'stock reservation',
                'verbose_name_plural': 'stock reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase / Receipt'), ('return', 'Customer Return'), ('exchange_in', 'Exchange — Incoming'), ('adjustment_in', 'Manual Adjustment In'), ('transfer_in', 'Transfer In'), ('sale', 'Sale'), ('exchange_out', 'Exchange — Outgoing'), ('adjustment_out', 'Manual Adjustment Out'), ('damage', 'Damaged / Shrinkage'), ('transfer_out', 'Transfer Out'), ('reservation', 'Reservation'), ('reservation_release', 'Reservation Release'), ('reservation_commit', 'Reservation Commit → Sale')], db_index=True, max_length=30)),
                ('reference_type', models.CharField(choices=[('order', 'Order'), ('return', 'Return'), ('exchange', 'Exchange'), ('transfer', 'Transfer'), ('manual', 'Manual'), ('system', 'System')], db_index=True, max_length=20)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Order ID, Return ID, etc.', max_length=100)),
                ('quantity', models.IntegerField(help_text='Positive = stock in. Negative = stock out.')),
                ('on_hand_after', models.IntegerField()),
                ('reserved_after', models.IntegerField()),
                ('available_after', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.warehousestock')),
            ],
            options={
                'verbose_name': 'stock ledger entry',
                'verbose_name_plural': 'stock ledger entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['variant', 'warehouse'], name='inventory_w_variant_8c335b_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['available'], name='inventory_w_availab_eef05c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('variant', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['reference_type', 'reference_id', 'status'], name='inventory_s_referen_7be914_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['stock_record', 'status'], name='inventory_s_stock_r_e47057_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('stock_record', 'reference_id'), name='unique_active_reservation_per_reference'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['stock_record', 'movement_type'], name='inventory_s_stock_r_add8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_6e609d_idx'),
        ),
    ]
