services:
  db:
      image: postgres:15-alpine
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - .env
      environment:
        - POSTGRES_DB=${POSTGRES_DB:-aurora_db}
        - POSTGRES_USER=${POSTGRES_USER:-aurora_user}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-aurora_user} -d ${POSTGRES_DB:-aurora_db}"]
        interval: 5s
        timeout: 5s
        retries: 5
      expose:
        - 5432

  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-aurora_user}:${POSTGRES_PASSWORD:-your_password}@db:5432/${POSTGRES_DB:-aurora_db}
      DATABASE: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AUTO_CREATE_MIGRATIONS: "0"
      RUN_COLLECTSTATIC: "1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ./backend
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-aurora_user}:${POSTGRES_PASSWORD:-your_password}@db:5432/${POSTGRES_DB:-aurora_db}
      DATABASE: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AUTO_CREATE_MIGRATIONS: "0"
      RUN_COLLECTSTATIC: "0"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  default:
    name: aurora_network
