# Generated by Django 5.2.11 on 2026-03-26 08:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('badge_text', models.CharField(blank=True, max_length=60)),
                ('badge_bold', models.CharField(blank=True, max_length=40)),
                ('cta_label', models.CharField(default='Shop Now', max_length=40)),
                ('cta_url', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_banners/')),
                ('bg_color', models.CharField(default='#f5f0eb', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['order'],
            },
        ),
    ]
