# Generated by Django 5.2.11 on 2026-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='shape_color',
            field=models.CharField(default='#f4dab4', max_length=20),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='position',
            field=models.CharField(choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right'), ('dual-banner-left', 'Dual Banner Left (Blueberry)'), ('dual-banner-right', 'Dual Banner Right (Blueberry)')], max_length=40, unique=True),
        ),
    ]
