# Generated by Django 5.2.12 on 2026-03-26 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "health alert",
                "verbose_name_plural": "health alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheckResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("api", "API"),
                            ("payment", "Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("checked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "health check result",
                "verbose_name_plural": "health check results",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="healthalert",
            index=models.Index(fields=["component"], name="health_heal_compone_002463_idx"),
        ),
        migrations.AddIndex(
            model_name="healthalert",
            index=models.Index(
                fields=["is_resolved"], name="health_heal_is_reso_dc73c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthcheckresult",
            index=models.Index(
                fields=["source", "component", "checked_at"],
                name="health_heal_source_5caa15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthcheckresult",
            index=models.Index(fields=["status"], name="health_heal_status_2ca024_idx"),
        ),
        migrations.AddIndex(
            model_name="healthcheckresult",
            index=models.Index(
                fields=["component"], name="health_heal_compone_0309e2_idx"
            ),
        ),
    ]
