# Generated by Django 5.2.12 on 2026-03-25 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('apps.notifications.events', 'Apps.Notifications.Events'), ('account_created', 'Account Created'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('order_placed', 'Order Placed'), ('order_paid', 'Order Paid'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_completed', 'Order Completed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('return_submitted', 'Return Submitted'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_refund_initiated', 'Return Refund Initiated'), ('return_completed', 'Return Completed'), ('exchange_submitted', 'Exchange Submitted'), ('exchange_approved', 'Exchange Approved'), ('exchange_shipped', 'Exchange Shipped'), ('exchange_completed', 'Exchange Completed'), ('low_stock_alert', 'Low Stock Alert'), ('out_of_stock', 'Out Of Stock')], db_index=True, max_length=60)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('context_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=15)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('send_at', models.DateTimeField(blank=True, help_text='If set, delivery is deferred until this time.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('success', models.BooleanField()),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'notification log',
                'verbose_name_plural': 'notification logs',
                'ordering': ['attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('apps.notifications.events', 'Apps.Notifications.Events'), ('account_created', 'Account Created'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('order_placed', 'Order Placed'), ('order_paid', 'Order Paid'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_completed', 'Order Completed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('return_submitted', 'Return Submitted'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_refund_initiated', 'Return Refund Initiated'), ('return_completed', 'Return Completed'), ('exchange_submitted', 'Exchange Submitted'), ('exchange_approved', 'Exchange Approved'), ('exchange_shipped', 'Exchange Shipped'), ('exchange_completed', 'Exchange Completed'), ('low_stock_alert', 'Low Stock Alert'), ('out_of_stock', 'Out Of Stock')], db_index=True, max_length=60)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], db_index=True, max_length=20)),
                ('name', models.CharField(help_text='Internal reference name.', max_length=200)),
                ('subject_template', models.CharField(blank=True, help_text='Email subject (Django template syntax). Ignored for SMS/WhatsApp.', max_length=500)),
                ('body_template', models.TextField(help_text='Plain-text body (Django template syntax). Used for all channels.')),
                ('html_body_template', models.TextField(blank=True, help_text='HTML body for email. Sent as alternate MIME part.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'ordering': ['event', 'channel'],
                'unique_together': {('event', 'channel')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'event'], name='notificatio_user_id_e2ced2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'channel'], name='notificatio_status_4567f1_idx'),
        ),
    ]
