# Generated by Django 5.2.11 on 2026-03-27 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productstocknotifyrequest"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifySubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_notified", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("unsubscribe_token", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notify_subscriptions", to="catalog.product")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notify_subscriptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "notify subscription",
                "verbose_name_plural": "notify subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["product", "is_notified"], name="notificatio_product_9ca498_idx"),
                    models.Index(fields=["created_at", "is_notified"], name="notificatio_created_b0cbfe_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("user__isnull", False)), fields=("product", "user"), name="uniq_notify_subscription_product_user"),
                    models.UniqueConstraint(condition=models.Q(("email__gt", "")), fields=("product", "email"), name="uniq_notify_subscription_product_email"),
                ],
            },
        ),
    ]
