# Generated by Django 5.2.12 on 2026-03-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifysubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notifysubscription',
            new_name='notificatio_product_0650fc_idx',
            old_name='notificatio_product_9ca498_idx',
        ),
        migrations.RenameIndex(
            model_name='notifysubscription',
            new_name='notificatio_created_b8603c_idx',
            old_name='notificatio_created_b0cbfe_idx',
        ),
    ]
