# Generated by Django 5.2.11 on 2026-03-29 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_seed_notification_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['attempted_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['key', 'event', 'channel']},
        ),
        migrations.AlterModelOptions(
            name='notifysubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_e2ced2_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_status_4567f1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='context_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='html_body_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject_template',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'status'], name='notificatio_event_t_97a51f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_289841_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'event_type'], name='notificatio_user_id_b16834_idx'),
        ),
    ]
