# Generated by Django 5.2.11 on 2026-03-29 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_alter_notification_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactQuery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("read", "Read"), ("resolved", "Resolved")],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("source", models.CharField(blank=True, default="web", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="notificatio_status_df7aaa_idx"),
                    models.Index(fields=["is_read", "created_at"], name="notificatio_is_read_ddb7be_idx"),
                ],
            },
        ),
    ]
