# Generated by Django 5.2.11 on 2026-03-29 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_seed_notification_ui_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('smtp', 'SMTP'), ('brevo', 'Brevo'), ('twilio', 'Twilio'), ('internal', 'Internal'), ('other', 'Other')], max_length=20, unique=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], max_length=20)),
                ('last_test_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at', '-attempted_at']},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='attempts_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], db_index=True, default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('order_confirmed', 'Order Confirmed'), ('reset_password', 'Reset Password'), ('shipping_update', 'Shipping Update'), ('refund', 'Refund'), ('contact', 'Contact'), ('product_notify', 'Product Notify'), ('custom', 'Custom')], db_index=True, default='custom', max_length=40),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='plain_text_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('brevo', 'Brevo'), ('twilio', 'Twilio'), ('internal', 'Internal'), ('other', 'Other')], db_index=True, default='smtp', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='rendered_context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='rendered_html_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='template_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='html_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='text_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_f70f70_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['provider', 'status'], name='notificatio_provide_83fbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_8fa9d0_idx'),
        ),
    ]
