# Generated by Django 5.2.12 on 2026-03-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_seed_notification_dashboard_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(blank=True, choices=[('order.created', 'order.created'), ('order.shipped', 'order.shipped'), ('order.delivered', 'order.delivered'), ('user.forgot_password', 'user.forgot_password'), ('user.blocked', 'user.blocked'), ('contact.form.submitted', 'contact.form.submitted'), ('product.notify_me', 'product.notify_me'), ('product.restocked', 'product.restocked'), ('order_paid', 'order_paid'), ('order_processing', 'order_processing'), ('order_cancelled', 'order_cancelled'), ('order_completed', 'order_completed'), ('payment_failed', 'payment_failed'), ('payment_refunded', 'payment_refunded'), ('return_submitted', 'return_submitted'), ('return_approved', 'return_approved'), ('return_rejected', 'return_rejected'), ('return_refund_initiated', 'return_refund_initiated'), ('return_completed', 'return_completed'), ('exchange_submitted', 'exchange_submitted'), ('exchange_approved', 'exchange_approved'), ('exchange_shipped', 'exchange_shipped'), ('exchange_completed', 'exchange_completed'), ('low_stock_alert', 'low_stock_alert'), ('out_of_stock', 'out_of_stock')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(blank=True, choices=[('order.created', 'order.created'), ('order.shipped', 'order.shipped'), ('order.delivered', 'order.delivered'), ('user.forgot_password', 'user.forgot_password'), ('user.blocked', 'user.blocked'), ('contact.form.submitted', 'contact.form.submitted'), ('product.notify_me', 'product.notify_me'), ('product.restocked', 'product.restocked'), ('order_paid', 'order_paid'), ('order_processing', 'order_processing'), ('order_cancelled', 'order_cancelled'), ('order_completed', 'order_completed'), ('payment_failed', 'payment_failed'), ('payment_refunded', 'payment_refunded'), ('return_submitted', 'return_submitted'), ('return_approved', 'return_approved'), ('return_rejected', 'return_rejected'), ('return_refund_initiated', 'return_refund_initiated'), ('return_completed', 'return_completed'), ('exchange_submitted', 'exchange_submitted'), ('exchange_approved', 'exchange_approved'), ('exchange_shipped', 'exchange_shipped'), ('exchange_completed', 'exchange_completed'), ('low_stock_alert', 'low_stock_alert'), ('out_of_stock', 'out_of_stock')], db_index=True, max_length=100),
        ),
    ]
