location /media/ {
    alias /app/media/;
    access_log off;
    expires 365d;
    add_header Cache-Control "public, max-age=31536000, immutable";
}

location ~* \.(?:avif|webp|jpg|jpeg|png|gif|svg|ico)$ {
    expires 365d;
    add_header Cache-Control "public, max-age=31536000, immutable";
}

