# Generated by Django 5.2.11 on 2026-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('placed', 'Placed'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=25),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=25),
        ),
    ]
