# Generated by Django 5.2.11 on 2026-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('cashfree', 'Cashfree'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
