# Generated by Codex on 2026-04-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_address_accounts_unique_default_address_per_type"),
        ("orders", "0006_alter_order_payment_method_phonepe"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_method",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("local_delivery", "Local Delivery"),
                    ("nimbuspost", "NimbusPost"),
                    ("shiprocket", "Shiprocket"),
                ],
                db_index=True,
                default="unassigned",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_approval_status",
            field=models.CharField(
                choices=[
                    ("pending_shipping_approval", "Pending Shipping Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending_shipping_approval",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_approved_orders",
                to="accounts.user",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["shipping_approval_status", "fulfillment_method"],
                name="orders_orde_shippin_8fc97a_idx",
            ),
        ),
    ]
