# Generated by Django 5.2.17 on 2026-09-01 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_approval_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_shippin_46c6dc_idx',
            old_name='orders_orde_shippin_8fc97a_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('online', 'Online'), ('pos', 'Point of sale')], db_index=True, default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Walk-in customer name. Kept on the order even when no account exists.', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Phone is the identity at the counter — this is what customer lookup matches on.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member who rang up this sale. Null for online orders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilment_type',
            field=models.CharField(choices=[('ship', 'Ship to customer'), ('carry_away', 'Carried away from counter')], db_index=True, default='ship', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_discount_approved_by',
            field=models.ForeignKey(blank=True, help_text='Set when the discount exceeded the staff ceiling and a manager authorised it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_discount_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=25),
        ),
    ]
