# Generated by Django 5.2.17 on 2026-09-01 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pos_order_fields'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_shift',
            field=models.ForeignKey(blank=True, help_text='The trading session this sale belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.posshift'),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.posterminal'),
        ),
    ]
