# Generated by Django 5.2.17 on 2026-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_pos_shift_order_pos_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('cash', 'Cash at counter'), ('cashfree', 'Cashfree'), ('razorpay', 'Razorpay'), ('phonepe', 'PhonePe'), ('stripe', 'Stripe'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
