# Generated by Django 5.2.11 on 2026-04-02 10:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_status', models.CharField(choices=[('accepted_all', 'Accepted all'), ('rejected_all', 'Rejected all'), ('customized', 'Customized'), ('withdrawn', 'Withdrawn')], max_length=32)),
                ('consent_version', models.CharField(default='1.0', max_length=32)),
                ('source', models.CharField(choices=[('banner', 'Banner'), ('settings_modal', 'Settings modal'), ('withdrawal', 'Withdrawal')], default='banner', max_length=32)),
                ('necessary', models.BooleanField(default=True)),
                ('analytics', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('preferences', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consented_at', '-created_at'],
                'indexes': [models.Index(fields=['consented_at'], name='privacy_con_consent_b16e35_idx'), models.Index(fields=['consent_status', 'consented_at'], name='privacy_con_consent_d7cabb_idx'), models.Index(fields=['anonymous_id', 'consented_at'], name='privacy_con_anonymo_efe57a_idx'), models.Index(fields=['session_key', 'consented_at'], name='privacy_con_session_1f60b6_idx')],
            },
        ),
    ]
