# Generated by Django 5.2.11 on 2026-04-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(max_length=128)),
                ('session_id', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('consent_status', models.CharField(choices=[('accepted_all', 'Accepted all'), ('rejected_all', 'Rejected all'), ('customized', 'Customized')], max_length=32)),
                ('consent_version', models.CharField(default='1.0', max_length=32)),
                ('category_necessary', models.BooleanField(default=True)),
                ('category_analytics', models.BooleanField(default=False)),
                ('category_marketing', models.BooleanField(default=False)),
                ('category_preferences', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('banner', 'Banner'), ('settings_modal', 'Settings modal')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConsentLog',
        ),
        migrations.AddIndex(
            model_name='cookieconsentlog',
            index=models.Index(fields=['created_at'], name='privacy_coo_created_ad7f24_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsentlog',
            index=models.Index(fields=['anonymous_id'], name='privacy_coo_anonymo_c8d9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsentlog',
            index=models.Index(fields=['consent_status'], name='privacy_coo_consent_583d8f_idx'),
        ),
    ]
