# Generated by Codex on 2026-03-25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="offer_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Offer ends at this datetime.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="offer_is_active",
            field=models.BooleanField(
                default=False,
                help_text="Master switch for offer availability.",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="offer_label",
            field=models.CharField(
                blank=True,
                help_text="Optional label like 'Flash Sale'.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="offer_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Limited-time offer price.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="offer_starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Offer starts at this datetime.",
                null=True,
            ),
        ),
    ]

