# Generated by Codex on 2026-03-25

import uuid
from django.db import migrations, models
import django.db.models.deletion


def backfill_global_attributes(apps, schema_editor):
    Attribute = apps.get_model("catalog", "Attribute")
    AttributeValue = apps.get_model("catalog", "AttributeValue")
    GlobalAttribute = apps.get_model("catalog", "GlobalAttribute")
    GlobalAttributeOption = apps.get_model("catalog", "GlobalAttributeOption")
    ProductAttributeConfig = apps.get_model("catalog", "ProductAttributeConfig")

    global_by_name = {}
    attrs = Attribute.objects.select_related("product").all().order_by("sort_order", "name")

    for attribute in attrs:
        key = (attribute.name or "").strip().lower()
        if not key:
            continue

        global_attr = global_by_name.get(key)
        if global_attr is None:
            global_attr = GlobalAttribute.objects.filter(name__iexact=attribute.name.strip()).first()
            if global_attr is None:
                global_attr = GlobalAttribute.objects.create(
                    name=attribute.name.strip(),
                    sort_order=attribute.sort_order or 0,
                    is_active=True,
                )
            global_by_name[key] = global_attr

        ProductAttributeConfig.objects.get_or_create(
            product_id=attribute.product_id,
            global_attribute_id=global_attr.id,
            defaults={
                "sort_order": attribute.sort_order or 0,
                "is_active": True,
            },
        )

        values = AttributeValue.objects.filter(attribute_id=attribute.id).order_by("sort_order", "value")
        option_map = {
            (opt.value or "").strip().lower(): opt
            for opt in GlobalAttributeOption.objects.filter(global_attribute_id=global_attr.id)
        }
        for idx, value in enumerate(values):
            option_key = (value.value or "").strip().lower()
            if not option_key:
                continue
            if option_key in option_map:
                option = option_map[option_key]
                if option.sort_order != (value.sort_order or idx):
                    option.sort_order = value.sort_order or idx
                    option.save(update_fields=["sort_order", "updated_at"])
                continue
            created = GlobalAttributeOption.objects.create(
                global_attribute_id=global_attr.id,
                value=value.value.strip(),
                sort_order=value.sort_order or idx,
                is_active=True,
            )
            option_map[option_key] = created


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productvariant_offer_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAttribute",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "global attribute",
                "verbose_name_plural": "global attributes",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GlobalAttributeOption",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=100)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("global_attribute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="catalog.globalattribute")),
            ],
            options={
                "verbose_name": "global attribute option",
                "verbose_name_plural": "global attribute options",
                "ordering": ["sort_order", "value"],
                "unique_together": {("global_attribute", "value")},
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeConfig",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("global_attribute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_configs", to="catalog.globalattribute")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="global_attribute_configs", to="catalog.product")),
            ],
            options={
                "verbose_name": "product attribute config",
                "verbose_name_plural": "product attribute configs",
                "ordering": ["sort_order", "global_attribute__name"],
                "unique_together": {("product", "global_attribute")},
            },
        ),
        migrations.RunPython(backfill_global_attributes, migrations.RunPython.noop),
    ]
