# Generated by Django 5.2.11 on 2026-03-27 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_avg_rating_product_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('value', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'product info item',
                'verbose_name_plural': 'product info items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
