# Generated by Django 5.2.11 on 2026-03-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productinfoitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStockNotifyRequest",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("is_notified", models.BooleanField(db_index=True, default=False)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_notify_requests", to="catalog.product")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_notify_requests", to=settings.AUTH_USER_MODEL)),
                ("variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_notify_requests", to="catalog.productvariant")),
            ],
            options={
                "verbose_name": "product stock notify request",
                "verbose_name_plural": "product stock notify requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["product", "created_at"], name="catalog_pro_product_ef8b45_idx"),
                    models.Index(fields=["variant", "created_at"], name="catalog_pro_variant_756a6c_idx"),
                    models.Index(fields=["user", "created_at"], name="catalog_pro_user_id_48c920_idx"),
                ],
            },
        ),
    ]
