# Generated by Django 5.2.12 on 2026-03-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productstocknotifyrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productstocknotifyrequest',
            new_name='catalog_pro_product_d93274_idx',
            old_name='catalog_pro_product_ef8b45_idx',
        ),
        migrations.RenameIndex(
            model_name='productstocknotifyrequest',
            new_name='catalog_pro_variant_006d4d_idx',
            old_name='catalog_pro_variant_756a6c_idx',
        ),
        migrations.RenameIndex(
            model_name='productstocknotifyrequest',
            new_name='catalog_pro_user_id_dd74ab_idx',
            old_name='catalog_pro_user_id_48c920_idx',
        ),
    ]
