# Generated by Django 5.2.11 on 2026-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_catalog_pro_product_ef8b45_idx_catalog_pro_product_d93274_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_backorder',
            field=models.BooleanField(default=False),
        ),
    ]
