# Generated by Django 5.2.11 on 2026-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'address_type'), name='accounts_unique_default_address_per_type'),
        ),
    ]
