# Generated by Django 5.2.12 on 2026-03-28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("shiprocket", "Shiprocket")], db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("awb_assigned", "AWB Assigned"),
                            ("pickup_requested", "Pickup Requested"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("rto", "RTO"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                            ("exception", "Exception"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=30,
                    ),
                ),
                ("external_order_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("external_shipment_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("awb_code", models.CharField(blank=True, db_index=True, max_length=120)),
                ("courier_name", models.CharField(blank=True, max_length=120)),
                ("courier_company_id", models.CharField(blank=True, max_length=120)),
                ("tracking_url", models.URLField(blank=True)),
                ("label_url", models.URLField(blank=True)),
                ("manifest_url", models.URLField(blank=True)),
                ("invoice_url", models.URLField(blank=True)),
                ("pickup_requested", models.BooleanField(default=False)),
                ("pickup_scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("raw_provider_response", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("webhook", "Webhook"), ("poller", "Poller"), ("manual", "Manual"), ("system", "System")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("provider_status", models.CharField(blank=True, max_length=120)),
                (
                    "internal_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "Created"),
                            ("awb_assigned", "AWB Assigned"),
                            ("pickup_requested", "Pickup Requested"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("rto", "RTO"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                            ("exception", "Exception"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_payload", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["provider"], name="shipping_sh_provide_123da0_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["awb_code"], name="shipping_sh_awb_cod_6606a7_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["external_shipment_id"], name="shipping_sh_externa_4301bd_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="shipping_sh_status_0644c6_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["created_at"], name="shipping_sh_created_93a1f0_idx"),
        ),
        migrations.AddConstraint(
            model_name="shipmentevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("idempotency_key",),
                name="shipping_unique_event_idempotency_key",
            ),
        ),
    ]
