# Generated by Django 5.2.12 on 2026-03-28

import json

from django.db import migrations


def seed_shipping_settings(apps, schema_editor):
    AppSetting = apps.get_model("features", "AppSetting")

    settings = [
        {
            "key": "shipping.provider",
            "value": json.dumps(
                {
                    "active": "shiprocket",
                    "enabled": True,
                    "auto_create_shipment": True,
                    "auto_generate_awb": True,
                    "auto_request_pickup": False,
                    "serviceability_check_enabled": False,
                    "polling_interval_minutes": 30,
                    "retry": {"max_retries": 5, "base_delay_seconds": 60},
                    "default_package": {
                        "weight_kg": 0.3,
                        "length_cm": 12,
                        "breadth_cm": 12,
                        "height_cm": 4,
                    },
                }
            ),
            "value_type": "json",
            "category": "shipping",
            "label": "Shipping Provider",
            "description": "Provider-level logistics orchestration config",
            "is_public": False,
            "is_editable": True,
        },
        {
            "key": "shipping.provider.schema",
            "value": json.dumps(
                {
                    "title": "Shipping Provider",
                    "description": "Provider orchestration settings",
                    "fields": {
                        "enabled": {"type": "toggle", "label": "Enabled", "default": True},
                        "active": {
                            "type": "select",
                            "label": "Active Provider",
                            "required": True,
                            "options": [{"label": "Shiprocket", "value": "shiprocket"}],
                            "default": "shiprocket",
                        },
                        "auto_create_shipment": {"type": "toggle", "label": "Auto Create Shipment", "default": True},
                        "auto_generate_awb": {"type": "toggle", "label": "Auto Generate AWB", "default": True},
                        "auto_request_pickup": {"type": "toggle", "label": "Auto Request Pickup", "default": False},
                        "serviceability_check_enabled": {"type": "toggle", "label": "Serviceability Check", "default": False},
                        "polling_interval_minutes": {"type": "text", "label": "Tracking Polling Interval (minutes)", "default": "30"},
                    },
                }
            ),
            "value_type": "json",
            "category": "shipping",
            "label": "Shipping Provider Schema",
            "description": "Schema for shipping.provider",
            "is_public": False,
            "is_editable": True,
        },
        {
            "key": "shipping.shiprocket",
            "value": json.dumps(
                {
                    "enabled": True,
                    "api_user_email": "",
                    "api_user_password": "",
                    "pickup_location": "Primary",
                    "pickup_pincode": "",
                    "channel_id": "",
                    "pickup_id": "",
                    "webhook_enabled": True,
                    "webhook_secret": "",
                    "sandbox_mode": False,
                    "auto_sync_tracking": True,
                    "default_payment_method_prepaid": "Prepaid",
                    "default_payment_method_cod": "COD",
                    "token_ttl_seconds": 86400,
                }
            ),
            "value_type": "json",
            "category": "shipping",
            "label": "Shiprocket",
            "description": "Shiprocket credentials and behavior settings",
            "is_public": False,
            "is_editable": True,
        },
        {
            "key": "shipping.shiprocket.schema",
            "value": json.dumps(
                {
                    "title": "Shiprocket",
                    "description": "Shiprocket API and webhook settings",
                    "fields": {
                        "enabled": {"type": "toggle", "label": "Enabled", "default": True},
                        "api_user_email": {"type": "text", "label": "API User Email", "required": True},
                        "api_user_password": {"type": "password", "label": "API User Password", "required": True},
                        "pickup_location": {"type": "text", "label": "Pickup Location", "default": "Primary"},
                        "pickup_pincode": {"type": "text", "label": "Pickup Pincode"},
                        "channel_id": {"type": "text", "label": "Channel ID"},
                        "pickup_id": {"type": "text", "label": "Pickup ID"},
                        "webhook_enabled": {"type": "toggle", "label": "Webhook Enabled", "default": True},
                        "webhook_secret": {"type": "password", "label": "Webhook Secret"},
                        "sandbox_mode": {"type": "toggle", "label": "Sandbox Mode", "default": False},
                        "auto_sync_tracking": {"type": "toggle", "label": "Auto Sync Tracking", "default": True},
                        "default_payment_method_prepaid": {"type": "text", "label": "Prepaid Payment Method", "default": "Prepaid"},
                        "default_payment_method_cod": {"type": "text", "label": "COD Payment Method", "default": "COD"},
                    },
                }
            ),
            "value_type": "json",
            "category": "shipping",
            "label": "Shiprocket Schema",
            "description": "Schema for shipping.shiprocket",
            "is_public": False,
            "is_editable": True,
        },
        {
            "key": "shipping.standard",
            "value": json.dumps({"flat_rate": 0, "free_shipping_threshold": 0}),
            "value_type": "json",
            "category": "shipping",
            "label": "Standard Shipping Pricing",
            "description": "Existing website shipping pricing rules",
            "is_public": False,
            "is_editable": True,
        },
        {
            "key": "shipping.standard.schema",
            "value": json.dumps(
                {
                    "title": "Standard Shipping",
                    "description": "Website shipping charge settings",
                    "fields": {
                        "flat_rate": {"type": "text", "label": "Flat Rate", "default": "0"},
                        "free_shipping_threshold": {"type": "text", "label": "Free Shipping Threshold", "default": "0"},
                    },
                }
            ),
            "value_type": "json",
            "category": "shipping",
            "label": "Standard Shipping Schema",
            "description": "Schema for shipping.standard",
            "is_public": False,
            "is_editable": True,
        },
    ]

    for row in settings:
        AppSetting.objects.update_or_create(key=row["key"], defaults=row)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0001_initial"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_shipping_settings, noop),
    ]
