# Generated by Codex on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0002_seed_shipping_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="local_delivery_status",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="shipment",
            name="local_expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="local_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="local_rider_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="shipment",
            name="local_rider_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("shiprocket", "Shiprocket"),
                    ("nimbuspost", "NimbusPost"),
                    ("local_delivery", "Local Delivery"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("created", "Created"),
                    ("booked", "Booked"),
                    ("assigned", "Assigned"),
                    ("awb_assigned", "AWB Assigned"),
                    ("pickup_requested", "Pickup Requested"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("rto", "RTO"),
                    ("returned", "Returned"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                    ("exception", "Exception"),
                ],
                db_index=True,
                default="created",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentevent",
            name="internal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("created", "Created"),
                    ("booked", "Booked"),
                    ("assigned", "Assigned"),
                    ("awb_assigned", "AWB Assigned"),
                    ("pickup_requested", "Pickup Requested"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("rto", "RTO"),
                    ("returned", "Returned"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                    ("exception", "Exception"),
                ],
                max_length=30,
            ),
        ),
    ]
