# Generated by Codex on 2026-04-11

import json

from django.db import migrations


def seed_multi_provider_settings(apps, schema_editor):
    AppSetting = apps.get_model("features", "AppSetting")

    provider_value = {
        "active": "shiprocket",
        "enabled": True,
        "auto_create_shipment": False,
        "auto_generate_awb": True,
        "auto_request_pickup": False,
        "serviceability_check_enabled": False,
        "polling_interval_minutes": 30,
        "retry": {"max_retries": 5, "base_delay_seconds": 60},
        "default_package": {"weight_kg": 0.3, "length_cm": 12, "breadth_cm": 12, "height_cm": 4},
    }

    provider_schema = {
        "title": "Shipping Provider",
        "description": "Provider orchestration settings",
        "fields": {
            "enabled": {"type": "toggle", "label": "Enabled", "default": True},
            "active": {
                "type": "select",
                "label": "Active Provider (legacy fallback)",
                "required": True,
                "options": [
                    {"label": "Shiprocket", "value": "shiprocket"},
                    {"label": "NimbusPost", "value": "nimbuspost"},
                    {"label": "Local Delivery", "value": "local_delivery"},
                ],
                "default": "shiprocket",
            },
            "auto_create_shipment": {"type": "toggle", "label": "Auto Create Shipment", "default": False},
            "auto_generate_awb": {"type": "toggle", "label": "Auto Generate AWB", "default": True},
            "auto_request_pickup": {"type": "toggle", "label": "Auto Request Pickup", "default": False},
            "serviceability_check_enabled": {"type": "toggle", "label": "Serviceability Check", "default": False},
            "polling_interval_minutes": {"type": "text", "label": "Tracking Polling Interval (minutes)", "default": "30"},
        },
    }

    nimbus_value = {
        "enabled": True,
        "base_url": "",
        "api_key": "",
        "webhook_enabled": True,
        "webhook_secret": "",
        "timeout_seconds": 20,
    }

    nimbus_schema = {
        "title": "NimbusPost",
        "description": "NimbusPost API and webhook settings",
        "fields": {
            "enabled": {"type": "toggle", "label": "Enabled", "default": True},
            "base_url": {"type": "text", "label": "Base URL"},
            "api_key": {"type": "password", "label": "API Key"},
            "webhook_enabled": {"type": "toggle", "label": "Webhook Enabled", "default": True},
            "webhook_secret": {"type": "password", "label": "Webhook Secret"},
            "timeout_seconds": {"type": "text", "label": "Timeout (seconds)", "default": "20"},
        },
    }

    rows = [
        ("shipping.provider", provider_value, "Shipping Provider", "Provider-level logistics orchestration config"),
        ("shipping.provider.schema", provider_schema, "Shipping Provider Schema", "Schema for shipping.provider"),
        ("shipping.nimbuspost", nimbus_value, "NimbusPost", "NimbusPost credentials and behavior settings"),
        ("shipping.nimbuspost.schema", nimbus_schema, "NimbusPost Schema", "Schema for shipping.nimbuspost"),
    ]

    for key, value, label, description in rows:
        AppSetting.objects.update_or_create(
            key=key,
            defaults={
                "value_type": "json",
                "value": json.dumps(value),
                "category": "shipping",
                "label": label,
                "description": description,
                "is_public": False,
                "is_editable": True,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0003_multi_provider_and_local_delivery"),
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_multi_provider_settings, noop),
    ]
