# Generated by Django 5.2.12 on 2026-03-25 08:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower number = evaluated first. Rules with equal priority are all applied.')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON conditions that must all match for this rule to apply.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.CharField(choices=[('cod', 'Cash on Delivery Fee'), ('payment_gateway', 'Payment Gateway Fee'), ('handling', 'Handling / Packing Fee'), ('platform', 'Platform Fee'), ('surcharge', 'General Surcharge'), ('discount', 'Discount / Waiver')], max_length=25)),
                ('amount_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage of Subtotal')], default='flat', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Flat amount OR percentage rate (e.g. 2.5 for 2.5%).', max_digits=10)),
                ('is_negative', models.BooleanField(default=False, help_text='If true, this rule subtracts from the total (a discount/waiver).')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap the calculated fee at this amount.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'fee rule',
                'verbose_name_plural': 'fee rules',
                'ordering': ['priority', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower number = evaluated first. Rules with equal priority are all applied.')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON conditions that must all match for this rule to apply.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('flat', 'Flat Rate'), ('percentage', 'Percentage of Order Value'), ('weight_based', 'Weight Based (per kg)'), ('free_threshold', 'Free Above Threshold'), ('free', 'Always Free')], default='flat', max_length=20)),
                ('carrier', models.CharField(blank=True, help_text='e.g. FedEx, Delhivery, India Post', max_length=100)),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=3)),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=7)),
                ('is_additive', models.BooleanField(default=False, help_text='If true, this rule stacks on top of other matched shipping rules.')),
                ('flat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_threshold_amount', models.DecimalField(decimal_places=2, default=0, help_text='Order must be ≥ this value for FREE_THRESHOLD to kick in.', max_digits=12)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Cap the shipping charge at this amount.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'shipping rule',
                'verbose_name_plural': 'shipping rules',
                'ordering': ['priority', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower number = evaluated first. Rules with equal priority are all applied.')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON conditions that must all match for this rule to apply.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('gst', 'GST (India)'), ('vat', 'VAT'), ('igst', 'IGST (Inter-state India)'), ('custom', 'Custom Tax')], default='gst', max_length=20)),
                ('tax_code', models.CharField(blank=True, help_text='e.g. GST-18, VAT-5', max_length=50)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Tax rate as a percentage (e.g. 18.000 for 18% GST).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_inclusive', models.BooleanField(default=False, help_text='If true, tax is already included in the product price.')),
                ('applies_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Categories'), ('product_type', 'Product Type')], default='all', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, related_name='tax_rules', to='catalog.category')),
            ],
            options={
                'verbose_name': 'tax rule',
                'verbose_name_plural': 'tax rules',
                'ordering': ['priority', 'name'],
                'abstract': False,
            },
        ),
    ]
