# Generated by Django 5.2.17 on 2026-09-01 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_pos_order_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short identifier printed on receipts, e.g. STALL-01.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'POS terminal',
                'verbose_name_plural': 'POS terminals',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='POSShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, help_text='Cash counted into the drawer at open.', max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='counted - expected. Negative is short.', max_digits=12, null=True)),
                ('close_note', models.CharField(blank=True, max_length=255)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_shifts_opened', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='pos.posterminal')),
            ],
            options={
                'verbose_name': 'POS shift',
                'verbose_name_plural': 'POS shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='POSCashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('pay_in', 'Pay in'), ('pay_out', 'Pay out'), ('refund', 'Cash refund to customer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_cash_movements', to='orders.order')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='pos.posshift')),
            ],
            options={
                'verbose_name': 'POS cash movement',
                'verbose_name_plural': 'POS cash movements',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_movement_amount_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='posshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('terminal',), name='uniq_open_shift_per_terminal'),
        ),
    ]
