# Generated by Django 5.2.12 on 2026-03-25 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, help_text="e.g. 'stripe', 'cashfree'", max_length=50)),
                ('provider_ref', models.CharField(blank=True, db_index=True, help_text="Provider's transaction/order ID", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('retry', 'Retrying')], db_index=True, default='pending', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_url', models.TextField(blank=True, help_text='Redirect URL for hosted pages')),
                ('client_secret', models.TextField(blank=True, help_text='Stripe client_secret')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('raw_headers', models.JSONField(default=dict)),
                ('raw_payload', models.TextField()),
                ('provider_event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('order_ref', models.CharField(blank=True, max_length=255)),
                ('event_status', models.CharField(blank=True, max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='provider + provider_event_id — guard against duplicate delivery', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'webhook log',
                'verbose_name_plural': 'webhook logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhooklog',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='unique_webhook_idempotency'),
        ),
    ]
