# Generated by Django 5.2.11 on 2026-03-28 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_refunded_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'ordering': ['-created_at'],
            },
        ),
    ]
