# Generated by Django 5.2.12 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymenttransaction_razorpay_checkout_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                    ("cancelled", "Cancelled"),
                    ("retry", "Retrying"),
                ],
                db_index=True,
                default="pending",
                max_length=25,
            ),
        ),
    ]
