# Generated by Django 5.2.17 on 2026-09-01 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pos_order_fields'),
        ('payments', '0005_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('online', 'Online checkout'), ('upi', 'UPI'), ('cash', 'Cash'), ('card', 'Card machine'), ('bank_upi', 'Direct bank UPI')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('voided', 'Voided')], db_index=True, default='captured', max_length=20)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_given', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=50)),
                ('provider_ref', models.CharField(blank=True, db_index=True, help_text='Provider payment id. Unique per provider — this is what makes webhook redelivery idempotent.', max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Staff member who took the money. Null for online orders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_tenders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='orders.order')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'order tender',
                'verbose_name_plural': 'order tenders',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_or_order_i_6becf1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_ref__gt', '')), fields=('provider', 'provider_ref'), name='uniq_tender_provider_ref'), models.CheckConstraint(condition=models.Q(('amount_applied', 0), _negated=True), name='tender_amount_nonzero')],
            },
        ),
    ]
