# Generated by Django 5.2.17 on 2026-09-01 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_backfill_order_tenders'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertender',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='The trading session this money belongs to. Cash without a shift cannot be reconciled at close.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='pos.posshift'),
        ),
    ]
