# Generated by Django 5.2.6 on 2026-03-26

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_type", models.CharField(choices=[("admin", "Admin"), ("staff", "Staff"), ("customer", "Customer"), ("system", "System"), ("unknown", "Unknown")], db_index=True, max_length=20)),
                ("action", models.CharField(choices=[("CREATE", "Create"), ("UPDATE", "Update"), ("DELETE", "Delete"), ("LOGIN", "Login"), ("LOGOUT", "Logout"), ("STATUS_CHANGE", "Status Change")], db_index=True, max_length=20)),
                ("entity_type", models.CharField(db_index=True, max_length=60)),
                ("entity_id", models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("path", models.CharField(blank=True, max_length=500, null=True)),
                ("method", models.CharField(blank=True, max_length=16, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="activity_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="audit_activi_created_7f0b1f_idx"),
                    models.Index(fields=["user"], name="audit_activi_user_id_8120b4_idx"),
                    models.Index(fields=["action"], name="audit_activi_action_8f2bf1_idx"),
                    models.Index(fields=["entity_type"], name="audit_activi_entity__a88df9_idx"),
                    models.Index(fields=["entity_id"], name="audit_activi_entity__dbf638_idx"),
                    models.Index(fields=["entity_type", "entity_id"], name="audit_activi_entity__43d551_idx"),
                    models.Index(fields=["actor_type", "created_at"], name="audit_activi_actor_t_97b8ad_idx"),
                ],
            },
        ),
    ]
