# Generated by Django 5.2.12 on 2026-03-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_created_7a5871_idx',
            old_name='audit_activi_created_7f0b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_user_id_1c38a1_idx',
            old_name='audit_activi_user_id_8120b4_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_action_259cfa_idx',
            old_name='audit_activi_action_8f2bf1_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_entity__41c7d1_idx',
            old_name='audit_activi_entity__a88df9_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_entity__654679_idx',
            old_name='audit_activi_entity__dbf638_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_entity__5a526e_idx',
            old_name='audit_activi_entity__43d551_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_actor_t_b66f70_idx',
            old_name='audit_activi_actor_t_97b8ad_idx',
        ),
    ]
